### ISSUE TITLE
Remove FlameScans 

### ISSUE THREAD

**Issue by Ner0me** [pandeynmn/nmns-extensions#26]
The FlameScans website was taken down on 2023-10-19, there is no more source to pull chapters from.
s. https://flamescans.org/ ![image](https://github.com/pandeynmn/nmns-extensions/assets/24465396/294a6d24-6320-471e-9109-9166a001b558)

**Comment by rufioh** [comment]
they just changed their url to flamecomics.com

**Comment by Ner0me** [comment]
You're correct, didn't bother to keep up with them, just now read their new announcements.
Issue closed.
